#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(RALT(KC_Z), KC_Q, KC_D, KC_R, KC_W, KC_B, KC_J, KC_F, KC_U, KC_P, RALT(KC_L), RALT(KC_W), KC_LCTL, KC_A, KC_S, KC_H, KC_T, KC_G, KC_Y, KC_N, KC_E, KC_O, KC_I, KC_RCTL, KC_LSFT, KC_Z, KC_X, KC_M, KC_C, KC_V, KC_K, KC_L, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_NO, LT(1,KC_ESC), KC_ENT, LT(2,KC_SPC), KC_NO),
    [1] = LAYOUT(KC_LALT, KC_EXLM, KC_AT, KC_LCBR, KC_RCBR, KC_GRV, KC_QUOT, QK_MACRO_1, QK_MACRO_3, QK_MACRO_4, QK_MACRO_2, KC_RALT, KC_LGUI, KC_AMPR, KC_DLR, KC_LPRN, KC_RPRN, KC_PIPE, KC_COLN, KC_SCLN, QK_MACRO_5, QK_MACRO_6, KC_EQL, KC_RGUI, KC_TRNS, KC_PERC, KC_CIRC, KC_LBRC, KC_RBRC, KC_TILD, KC_DQUO, KC_HASH, QK_MACRO_7, QK_MACRO_8, KC_BSLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSPC, MO(3), KC_TRNS),
    [2] = LAYOUT(KC_LALT, KC_HOME, KC_PGUP, KC_UP, KC_PGDN, KC_END, KC_EQL, KC_P7, KC_P8, KC_P9, KC_PAST, KC_RALT, KC_LGUI, KC_INS, KC_LEFT, KC_DOWN, KC_RGHT, KC_DEL, KC_MINS, KC_P4, KC_P5, KC_P6, KC_PPLS, KC_RGUI, KC_TRNS, KC_VOLD, KC_MPRV, KC_MPLY, KC_MNXT, KC_VOLU, KC_MUTE, KC_P1, KC_P2, KC_P3, KC_TRNS, KC_TRNS, KC_TRNS, MO(3), KC_TAB, KC_TRNS, KC_P0),
    [3] = LAYOUT(UG_VALU, UG_SATU, UG_HUEU, UG_NEXT, KC_NO, UG_TOGG, KC_NUM, KC_F7, KC_F8, KC_F9, KC_F10, KC_NO, UG_VALD, UG_SATD, UG_HUED, UG_PREV, KC_NO, KC_NO, KC_NO, KC_F4, KC_F5, KC_F6, KC_F11, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_F12, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS)
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed) {
        switch (keycode) {
            case QK_MACRO_0:
                SEND_STRING("<=");
                return false;
            case QK_MACRO_1:
                SEND_STRING("=>");
                return false;
            case QK_MACRO_2:
                SEND_STRING("<-");
                return false;
            case QK_MACRO_3:
                SEND_STRING("->");
                return false;
            case QK_MACRO_4:
                SEND_STRING("<|");
                return false;
            case QK_MACRO_5:
                SEND_STRING("|>");
                return false;
            case QK_MACRO_6:
                SEND_STRING("=<<");
                return false;
            case QK_MACRO_7:
                SEND_STRING(">>=");
                return false;
        }
    }

    return true;
};


#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


